### ISSUE TITLE
x-ms-client-name not honored for query parameter 

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.modelerfour#145]
**Describe the issue**
I'm trying to rename a parameter with a transform in readme.md, however I'm not able to rename some parameters. For example working with this [swagger](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json), this transform doesn't seem to work:

```yaml
directive:
  - from: swagger-document
    where: $.paths..parameters[*]
    transform: >
      if ($.name === "showStats") {
        $["x-ms-client-name"] = "includeStatistics";
      }
```
However if I target a different parameter it works

```yaml
directive:
  - from: swagger-document
    where: $.paths..parameters[*]
    transform: >
      if ($.name === "input") {
        $["x-ms-client-name"] = "fooBar";
      }

```

It seems to be ignoring `x-ms-client-name` on query parameters, while body parameters honor it.

I ran autorest with `--interactive` and in the file just before the first codemodel file, I can see that the parameter has the `x-ms-client-name` property added in the transform
![image](https://user-images.githubusercontent.com/21109913/73566774-88e80680-4419-11ea-82e8-7b8355ecba96.png)

** REQUIRED ** 
**ModelerFour** version: 4.4.158
**AutoRest-core** version: 3.0.6192
**CommandLine** : autorest --typescript --use=<LOCAL_AUTOREST.TYPESCRIPT_REPO>
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json

**Comment by fearthecowboy** [comment]
modelerfour `4.6.186`+ should resolve this. Can you test it and see?

**Comment by joheredi** [comment]
@fearthecowboy, I tried with the following versions and the parameter is still not renamed
AutoRest core (3.0.6192)
AutoRest extension '@autorest/typescript' (local)
AutoRest extension '@autorest/modelerfour' (4.6.188->4.6.188)
