### ISSUE TITLE
Duplicated schema when generating storage blob management swagger.

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.modelerfour#205]
Input:
https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/blob.json

BlobServiceProperties is duplicated.

**Comment by iscai-msft** [comment]
also seeing this with InnerError when generating application insights 2015-05-01


https://github.com/Azure/azure-rest-api-specs/tree/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01

**Comment by fearthecowboy** [comment]
We tracked this down -- unusual in that the inner inlined model has an `x-ms-client-name` when it didn't need it, (which forced it to the same name as the parent)

We finally got the code that removes unreferenced flattened models automatically now, it's going thru CI and I'm going to have @lmazuel  test it with python before you should grab it.

**Comment by daviwil** [comment]
I just tried the storage spec with 4.10.240 and I only see one instance of `BlobStorageProperties` now.  @pakrym, give that version a try and let us know whether it resolves the issue for you.  Also @iscai-msft can you try the AppInsights spec again with this version and see if it resolves things?

**Comment by fearthecowboy** [comment]
There is also a case corrected by autorest-core `--version:3.0.6253`  -- secondary input files (ones that are `$ref`'d but not in `input-file` and had models that inherited from potentially polymorphic parents in primary files were getting kept. 6253 makes them only get kept it they have a discriminator on the object too.

**Comment by iscai-msft** [comment]
No, sadly it's still failing. Let me look into it a little bit more rn.

**Comment by iscai-msft** [comment]
I'm still running into a problem with two InnerError entries, they appear to be coming from these two swagger files:
1. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentAnnotations_API.json
2. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentWorkItemConfigs_API.json

**Comment by iscai-msft** [comment]
Both are now working. Applicationinsights ended up working after swagger changes, so this is no longer an issue Python side

**Comment by MiYanni** [comment]
Fixed from C# side for Storage spec.
