### ISSUE TITLE
Missing local API version

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.modelerfour#93]
https://github.com/Azure/autorest.testserver/blob/a5e6e2ef725df87c8981116836531a2f10be9128/swagger/azure-special-properties.json#L362-L371

M4:
![image](https://user-images.githubusercontent.com/1050156/70938699-895c4780-1ffb-11ea-90cb-309cebbb10a3.png)

M4 4.2.99, Core 3.0.6179, CMD 3.0.6149

**Comment by fearthecowboy** [comment]
Fixed in .106+  (the local part is, the global will be when #112 merges)

https://github.com/Azure/autorest.modelerfour/blob/master/modelerfour/test/scenarios/azure-special-properties/modeler.yaml#L1185

**Comment by fearthecowboy** [comment]
This should be in .108 too.

**Comment by lmazuel** [comment]
@fearthecowboy still don't see it :(
```
version: 3.0.6185
use-extension:
  "@autorest/modelerfour": "4.3.121"
```
autorest-beta 3.0.6149

**Comment by iscai-msft** [comment]
Hey @fearthecowboy, I've been looking into this issue on the autorest.python side in AzureSpecials, and the local api version ("2.0", using get_method_local_valid as the example)  is being listed as a query parameter and not under the apiVersions of that method.

Ask: Would it be possible to include those under the apiVersions? I do have the ability to add in logic to make the python code work with what's currently being given, but I think it would make more sense to include it under apiVersions, at least on the python side.

[get_method_local_valid]
![image](https://user-images.githubusercontent.com/43154838/76532606-3a348000-644d-11ea-9d20-c44baf96d86c.png)

[api_version query parameter]
![image](https://user-images.githubusercontent.com/43154838/76532634-46b8d880-644d-11ea-9cf3-fb244b5444c0.png)

**Comment by fearthecowboy** [comment]
This is a bit of a conundrum.

If the API version parameter value isn't the same as the `version` in `info` section of the swagger, it seems to me like it shouldn't be treated as an api-version parameter at all, and just handled as a regular parameter.

We have another issue #183 that needs to be explicitly treated too. 

I think the answer here is either a configuration or extension to mark a parameter as "don't mess with this, treat as a regular parameter" is necessary. 

WDYT?

**Comment by lmazuel** [comment]
Fixed with core 3.0.6258 and m4 4.10.246
